---
name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [master]

jobs:
  lint-and-tidy:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          args: ./...
          version: v2.1.0

      - name: Run tidy check
        run: |
          go mod tidy
          # Fail if go.mod or go.sum changed
          git diff --exit-code go.mod go.sum

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Run tests
        run: go test -v ./...

  oauth_e2e_test:
    name: OAuth E2E Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Pre-pull docker images
        run: |
          docker compose -f test/oauth/docker-compose.yaml pull --ignore-buildable --ignore-pull-failures
        timeout-minutes: 15
      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.4.2
        with:
          compose-file: test/oauth/docker-compose.yaml
          up-flags: --wait --wait-timeout 600
          compose-version: latest
        timeout-minutes: 20
      - name: Check metric scrape service status
        run: |
          status=$(docker compose -f test/oauth/docker-compose.yaml ps -aq check_metric_scrape | xargs docker inspect -f '{{.State.ExitCode}}')
          if [ "$status" -eq 0 ]; then
            echo "E2E test successful: check_metric_scrape exited with code 0."
          else
            echo "E2E test failed: check_metric_scrape exited with code $status."
            exit 1
          fi
